analytics: {}
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.529561
  lightness: 0.023595
  rhythmicContrast: 0.6335
  saturation: 0.716698
cta: {}
layout_spectrum: 0.998311
name: RyanHughes
opengraph: {}
purpose: {}
typography_spectrum: 0.911318
